# Generated by Django 4.0.1 on 2022-02-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('photo_book', models.ImageField(blank=b'I01\n', null=b'I01\n', upload_to='photos')),
                ('photo_author', models.ImageField(blank=b'I01\n', null=b'I01\n', upload_to='photos')),
                ('pages', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('price', models.DecimalField(blank=b'I01\n', decimal_places=2, max_digits=10, null=b'I01\n')),
                ('rental_price_day', models.DecimalField(blank=b'I01\n', decimal_places=2, max_digits=5, null=b'I01\n')),
                ('total_rental', models.DecimalField(blank=b'I01\n', decimal_places=2, max_digits=5, null=b'I01\n')),
                ('rental_period', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=b'I01\n', choices=[('available', 'available'), ('rental', 'rental'), ('sold', 'sold')], max_length=50, null=b'I01\n')),
                ('category', models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.PROTECT, to='Libary.category')),
            ],
        ),
    ]
